import 'package:flutter/material.dart';

const Color OVERLAY_COLOR = const Color(0x60000000);
const bool OVERLAY_DISMISSIBLE = true;
const Color MODAL_COLOR = const Color(0xffefefef);
const EdgeInsetsGeometry MODAL_MARGIN = const EdgeInsets.fromLTRB(24, 200, 24, 0);
const double MODAL_BORDER_RADIUS = 16;
const EdgeInsetsGeometry MODAL_CONTENT_PADDING_VERTICAL = const EdgeInsets.fromLTRB(0, 28, 0, 16);
const EdgeInsetsGeometry MODAL_CONTENT_PADDING_HORIZONTAL = const EdgeInsets.fromLTRB(16, 0, 16, 0);
const String MODAL_FONT_FAMILY = 'Roboto';
const double MODAL_TITLE_FONT_SIZE = 17;
const Color MODAL_TITLE_FONT_COLOR = const Color(0xff004a8f);
const EdgeInsetsGeometry MODAL_BODY_PADDING = const EdgeInsets.fromLTRB(0, 16, 0, 24);
const double MODAL_BODY_FONT_SIZE = 15;
const Color MODAL_BODY_FONT_COLOR = const Color(0xff000000);
const Color MODAL_DIVIDER_COLOR = const Color(0x2108141F);
const double MODAL_DIVIDER_SIZE = 0.5;
const EdgeInsetsGeometry MODAL_BUTTON_PADDING = const EdgeInsets.fromLTRB(0, 16, 0, 0);
const double MODAL_BUTTON_FONT_SIZE = 15;
const Color MODAL_BUTTON_FONT_COLOR = const Color(0xfff15a22);
